### ISSUE TITLE
Use-of-uninitialized-value in djpeg with MSAN (jpeg-v9c)

### ISSUE THREAD

**Issue by Tricker-z** [libjpeg-turbo/ijg#1]
Hi, developers of libjpeg:

Recently, I tested the binary djpeg instrumented with MSAN (in jpeg-v9c). Unfortunately, it incurred a crash with the following error information and I‘m not sure of the cause. Any help would be greatly appreciated from you :D

```
Corrupt JPEG data: 10 extraneous bytes before marker 0xdb
P6
6 15
255
==15969==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x562e829cc1c6 in h2v2_merged_upsample jdmerge.c
    #1 0x562e829ca817 in merged_2v_upsample jdmerge.c
    #2 0x562e82a50065 in process_data_simple_main jdmainct.c
    #3 0x562e82985468 in jpeg_read_scanlines (/workspace/jpeg-9c/djpeg+0xca468) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)
    #4 0x562e82961640 in main (/workspace/jpeg-9c/djpeg+0xa6640) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)
    #5 0x7f7e3205ad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #6 0x7f7e3205ae3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #7 0x562e828da304 in _start (/workspace/jpeg-9c/djpeg+0x1f304) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)

SUMMARY: MemorySanitizer: use-of-uninitialized-value jdmerge.c in h2v2_merged_upsample
Exiting
```

**Crash input**

Here is the file that triggers the error - [djpeg.tar.gz](https://github.com/libjpeg-turbo/ijg/files/9228102/djpeg.tar.gz)

Thanks & Best regards

**Comment by dcommander** [comment]
This repository is a reference for libjpeg-turbo developers. It is not maintained by the IJG. If you are trying to file a bug report against jpeg-9c, then you need to contact the IJG using the contact info provided in the jpeg-9c README file. The IJG does not have a GitHub repository. This project is libipeg-turbo, which is not the same thing as libjpeg. We forked from libjpeg before the current IJG maintainer took over from Tom Lane. As I mentioned in the other bug report you filed, I am happy to look into this issue if it is reproducible in libjpeg-turbo, but otherwise, you are reporting bugs in a completely different code base that we do not control.
